### ISSUE TITLE
Performance Issues with ElementsHive Plugins on the Website

### ISSUE THREAD

**Issue by felipecandian** [ElementsHive/elements-hive-for-breakdance-bugs#1] opened 2023-10-19 18:53 UTC
**Describe the bug**
Performance Issues with ElementsHive Plugins on the Website ||
WebGL Slideshows - problems with performance on GTMetrix (lighthouse) and GooglePage.

**To Reproduce**
Our website was developed using a combination of Breakdance along with both the free and Pro versions of ElementsHive. ElementsHive was employed in four different div sections on our site's index page, each serving a unique purpose:

Initial Banner with Entrance Animations
Two WebGL Slideshows
Footer with WebGL Wavy Gradients
The primary concern we'd like to address is the performance of the website. After conducting performance tests using tools like Geometrix, we received the results found in the attachements. Subsequently, we performed tests using Google PageSpeed Insights and obtained these results.

However, we've noticed a significant improvement in the results when we disable the ElementsHive plugins and rerun the tests.

**Expected behavior**
Improved performance in page loading and in GTmetrix and GooglePage. We are actively seeking solutions to optimize the website's performance while retaining the features and functionalities offered by ElementsHive. Any guidance or suggestions on how to enhance performance while using ElementsHive would be greatly appreciated.

**Screenshots or Screencasts**
https://youtu.be/g9Joj0_nL30
GTMetrix and Google Page without the plugin activated:
https://gtmetrix.com/reports/investandhealth.com/bxhgYTBi/
https://pagespeed.web.dev/analysis/https-investandhealth-com-dev2/tfczxe1wp9?form_factor=desktop

With the plugins activated:
https://pagespeed.web.dev/analysis/https-investandhealth-com-dev2/wl204xcdzi?form_factor=mobile

https://gtmetrix.com/?job_error=KYf6DT8z
![imagem_2023-10-19_155215125](https://github.com/ElementsHive/elements-hive-for-breakdance-bugs/assets/34189423/5b1dbee9-27f0-4c3a-b5b4-13f478369b47)

** Server :**
![imagem_2023-10-19_155310411](https://github.com/ElementsHive/elements-hive-for-breakdance-bugs/assets/34189423/dcc9aaba-32f3-4176-af26-2a1cea9c1a3e)

Wordpress: 6.3.2
Breakdance: 1.5.0
EH free: 1.3.4
Elements Hive Pro: 1.2.3
Staging website: [investandhealth.com/dev2/](http://investandhealth.com/dev2/)
Production website: [investandhealth.com/](http://investandhealth.com/dev2/)

** Client (please complete the following information):**
 - Browser OperaGX
 - Browser Version [e.g. 22]

**Additional context**

**Comment by MrBushid0** [comment] 2023-10-20 09:01
Hi Felipe, 

First just to reiterate what I mentioned in the FB group post you made https://www.facebook.com/groups/elementshiveforbreakdance/posts/890762029062693/

There are no inherent performance problems with Elements Hive Free or Pro versions. Otherwise, the hundreds of people already using them would have flooded this group and all other channels.

**GTMetrix Error (No CPU idle period)**

This is not a problem with EH but with GTMetrix's way of calculating. read the details here https://gtmetrix.com/blog/gtmetrix-lighthouse-errors/


**Performance Testing**

The pagespeed site is good for normal users with little knowledge. When you want to investigate a network performance problem, you want to have a lot more detailed technical data to help you understand the root cause(s).

_For the remainder of this thread. Please use webpagetest.org for reporting_  

**Baseline**

Please start by creating baseline tests and post the links to the results here so that everyone is on the same page. 

Use webpagetest.org, you should create a free account so that it autosaves your tests in the test history. 

Make sure you are using the same test config for all tests! 

1. Deactivate Elements Hive ( Free and Pro ) and run a test 
2. Add one of the default breakdance Scrolling Animations to any element on that page and run a test 
3. Deactivate the BD scrolling animation you enabled. Activate Elements Hive ( Free and Pro ) and run test 

Please include the links for the 3 tests above. 

Thanks

**Comment by MrBushid0** [comment] 2023-11-03 17:58
Hi Felipe, 

I'm closing the issue since you said on FB that you found the cause on your end. 

<img width="993" alt="Screenshot 2023-11-03 at 18 54 35" src="https://github.com/ElementsHive/elements-hive-for-breakdance-bugs/assets/3267657/edef11a9-5323-4cff-a78f-af04c69a4f05">


Please update the issue and the YouTube video with the actions you took as it may help other users in the future.

Thanks

**Closed as completed by MrBushid0** 2023-11-03 17:58 UTC
Labels: invalid :x:, Not an EH Issue :closed_book:
